kaspad_address: "127.0.0.1:16110"
block_wait_time: 1000
print_stats: true
log_to_file: true
health_check_port: ""
var_diff: true
var_diff_stats: true
pow2_clamp: true
extranonce_size: 2

instances:
  - stratum_port: ":5553"
    min_share_diff: 1024
    prom_port: ":2114"
    log_to_file: true
    shares_per_min: 30

  - stratum_port: ":5554"
    min_share_diff: 1024
    prom_port: ":2115"
    log_to_file: true
    shares_per_min: 20

  - stratum_port: ":5555"
    min_share_diff: 1024
    prom_port: ":2116"
    log_to_file: true
    shares_per_min: 20

  - stratum_port: ":5556"
    min_share_diff: 1024
    prom_port: ":2117"
    log_to_file: true
    shares_per_min: 20

  - stratum_port: ":5557"
    min_share_diff: 1024
    prom_port: ":2118"
    log_to_file: true
    shares_per_min: 20

  - stratum_port: ":5558"
    min_share_diff: 1024
    prom_port: ":2118"
    log_to_file: true
    shares_per_min: 20

